github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
repository: DILCISBoard/E-ARK-AIP
plugins:
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
